# Generated by Django 3.0.6 on 2020-05-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('description', models.CharField(max_length=160)),
                ('percent', models.FloatField()),
            ],
        ),
    ]
